### ISSUE TITLE
[git] git push 에러 발생 => [remote rejected] connot lock ref 

### ISSUE THREAD

**Issue by khsi12345** [Moka-react/Issues#1]
github remote branch는 아래와 같이 4가지 입니다.
[master, develop, feature/firebase, feature/styled]
 
git clone 후 제가 개발할 브랜치인 develop/yang을 만들고 git pull origin develop으로 develop을 pull 
받았습니다.

그리고 개발을 진행하고 add, commit 후 push를 했더니,
! [remote rejected]     develop/yang -> develop/yang (cannot lock ref 'refs/heads/develop/yang': 'refs/heads/develop' exists; cannot create 'refs/heads/develop/yang')
위와 같은 에러가 발생합니다.

구글링을 통해서 remote rejected 키워드로 검색 해봤고, cannot lock ref 'refs/heads/develop/yang': 'refs/heads/develop' exists; cannot create 'refs/heads/develop/yang' 이 문장으로도 검색을 해봤지만 해결을 못하고 있는 상황입니다.

그리고 해당 프로젝트 폴더를 제거하고 다시 클론을 받았습니다.
git branch develop/yang 명령어를 입력했더니, 
fatal: cannot lock ref 'refs/heads/develop/yang': 'refs/heads/develop' exists; cannot create 'refs/heads/develop/yang'
위와 같은 에러가 발생합니다.

도움 부탁드립니다....

**Comment by devGW** [comment]
소스트리 사용 중인가요?

**Comment by khsi12345** [comment]
devGW님
이미 폴더를 삭제하고 새롭게 클론 받은 상태여서 알려주신 rm ~~~ 명령어 입력하면
rm: .git/refs/heads/develop/yang: Not a directory 라고 뜨네요...
해결할 수 없는 강을 건넌거 같아요

**Comment by devGW** [comment]
깃허브 공개 가능한가요?
깃 폴더 아래 브랜치 확인해서 고쳐야 할거 같네요

**Comment by khsi12345** [comment]
회사 깃헙이어서 공개는 힘들어요 ㅠㅠ

**Comment by devGW** [comment]
논 외로 이슈 제목에 깃의 무슨 문제인지도 명시해주세요!

**Comment by khsi12345** [comment]
=======================================================================
devGW님이 알려준 명령어로 시도 해보았지만 에러 해결이 안되었습니다.
도저히 이 에러로 시간을 끌 수 없다고 판단, feature/yang으로 브랜치를 만들었고 push를 했는데 아무 에러도 뜨지 않고 정상적으로 푸쉬 완료되었습니다.

순간적으로 에러랑 연관 지어서 생각을 해봤었는데요.
이미 리모트에 develop 브랜치가 존재하기 때문에 develop/* 이와 같은 브랜치명은 사용할 수 없는것으로 추측했습니다. (구글 검색했을 때 소스 트리 사용하는 어떤 분의 글에서도 위와 같이 비슷하게 작성한 것을 확인.)

추측을 확신으로 만들기 위해 퇴근 후 테스트를 해봤습니다.
로컬에서 feature 브랜치를 생성 후 리모트로 git push => 리모트에 feature 브랜치 생성.
로컬에서 feature 브랜치에서 feature/* 브랜치명으로 브랜치 생성 시도 => develop 브랜치에서 develop/* 브랜치 생성하려고 했을때와 동일한 에러 발생!

결론 : 특정 문자열 브랜치가 존재한다면 (특정 문자열 브랜치)/* 이와 같은 브랜치명을 만들면 에러 발생, 
고로 만들 면 안된다 or 만들 수 없다.
