### ISSUE TITLE
[리엑트를 다루는 기술] LifeCycle 예제(146pg) 中 오류가 생겨 올립니다

### ISSUE THREAD

**Issue by flyyash** [Moka-react/Issues#33]
### 부가 설명
> color값이 null이어서 읽을수 없다는데 어떻게 수정해야 할까요

### 에러 문구
> 에러 문구를 작성해주세요

×
TypeError: Cannot read property 'color' of null
getDerivedStateFromProps
C:/Users/Desktop/hello-react/src/LifeCycleSample.js:19
  16 |    }
  17 | 
  18 |    static getDerivedStateFromProps(nextProps, prevState){
> 19 |        if(nextProps.color !== prevState.color){
     | ^  20 |            return { color: nextProps.color};
  21 |        }
  22 |        return null;

### 코드 구현 부
> 에러난 부분의 코드 또는 전체코드 적어주세요 

class LifeCycleSample extends Component{
    State = {
        number : 0,
        color : null,
    }

    myRef = null; // Ref 설정할 부분

    constructor(props){
    super(props);
    console.log('constructor')
    }

    static getDerivedStateFromProps(nextProps, prevState){
        if(nextProps.color !== prevState.color){
            return { color: nextProps.color};
        }
        return null;
    }

### Environment (optional)
> 프로젝트가 어떤 환경에서 실행 됐는지 적어주세요
- OS: windows 10
- Node Version: 14.1.0

**Comment by devGW** [comment]
State => state 로 바꿔주세요

**Comment by flyyash** [comment]
오타였다니..감사합니다
