### ISSUE TITLE
hooks 에서 여러개의 버튼에 개별로 onClick 이벤트를 주고 싶습니다.

### ISSUE THREAD

**Issue by zakdok** [Moka-react/Issues#35]
예를 들어

const [count, setCount] = useState(0)

    return (
        <>
                <button 
                    onClick={() => setCount(count + 1)}
                >
                    {count}
                </button>
                <button 
                    onClick={() => setCount(count + 1)}
                >
                    {count}
                </button>
     </>
)

이렇게 있을 때 첫번째 버튼과 두번째 버튼이 각자 고유한 count값을 가졌으면 좋겠는데 어떻게 하는지 좋을지 문서 공유 해주시면 감사하겠습니다..!

**Comment by devGW** [comment]
```js
const useCounter = (initialState) => {
  const [count, setCount] = useState(initialState)
  const increment = () => {
    setCount(count+1)
  }
  return {
    count,
    increment
  }
}
const { count, increment } = useCounter(0)

return (
    <>
            <button 
                onClick={increment}
            >
                {count}
            </button>
            <button 
                onClick={increment}
            >
                {count}
            </button>
 </>
```

문서 공유할건 없고 이렇게 하시면 됩니다.
